# yaml-language-server: $schema=devex/configs/yaml-schemas/sops.schema.json
# Identities (anchors). Add a new line per person/machine/agent.
keys:
  - &developer age1fl57s289zwvazhw84gx64sumpr0u2s5n90wtxt7repwqmljeu53s2rjg6s
  - &admin age1a2aym0wf0fekw3grk0u8deauwysepu8duq2zuxg4e8dyjw9jnccqa4p6m7

# Layout: devops/<project>/secrets/<secret-name>/<env>.yaml
creation_rules:
  - path_regex: devops/infra/secrets/developer-age-private-key\.yaml$
    key_groups:
      - age: [*admin]
  - path_regex: devops/infra/secrets/pulumi-passphrase/local\.yaml$
    key_groups:
      - age: [*developer]
  - path_regex: devops/matrix/secrets/pulumi-passphrase/local\.yaml$
    key_groups:
      - age: [*developer]
  - path_regex: devops/infra/secrets/pulumi-passphrase/prod\.yaml$
    key_groups:
      - age: [*developer]
  - path_regex: devops/matrix/secrets/pulumi-passphrase/prod\.yaml$
    key_groups:
      - age: [*developer]
  - path_regex: devops/infra/secrets/cloudflare-api-token/prod\.yaml$
    key_groups:
      - age: [*admin]
  - path_regex: devops/infra/secrets/google-oauth/prod\.yaml$
    key_groups:
      - age: [*admin]
