#!/usr/bin/env bash
set -euo pipefail
script_path=$(realpath "$0")
script_dir=$(dirname "${script_path}")
repo_root=$(git -C "${script_dir}" rev-parse --show-toplevel)
exec node "${repo_root}/devex/scripts/src/unt.ts" "$@"
