/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ApiKeys {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  key_hash: string;
  last_used_at: Timestamp | null;
  name: string;
  user_id: string;
}

export interface JiraConnections {
  access_token_expires_at: Timestamp;
  cloud_id: string;
  enc_access_token: string;
  enc_refresh_token: string;
  site_url: string;
  user_id: string;
}

export interface Sessions {
  expires_at: Timestamp;
  session_id: string;
  user_id: string;
}

export interface Tickets {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  jira_issue_key: string;
  project_key: string;
  user_id: string;
}

export interface Users {
  atlassian_account_id: string;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
}

export interface DB {
  api_keys: ApiKeys;
  jira_connections: JiraConnections;
  sessions: Sessions;
  tickets: Tickets;
  users: Users;
}
